### ISSUE TITLE
out-of-date F-Droid packages <= not-tagged releases

### ISSUE THREAD

**Issue by guillaume-d** [ligi/AJShA#2]
Because 0.11 and 0.12 are not tagged in GitHub (as 0.10 was) F-Droid can only offer 0.10 as the lastest installable version. On their Wiki it reads (emphasis mine):
> **We have the current version** of this app. (**Check mode: Tags**) (Auto-update mode: Version %v)
> The **current (recommended) version is 0.10** (version code 10). 

I guess the tags should be as follows:
- 0.12: effe4c0081c646edc54f27e6ec60642b01d3cafc
- 0.11: ae7034f404f9235055243a8fd46808fe7662cdf5

**Comment by ligi** [comment]
tags created - thanks!

**Comment by guillaume-d** [comment]
Thanks to you, that was quick!
Let's see when F-Droid pick them up (I have no idea how often or even if they poll).

**Comment by ligi** [comment]
should be soon: https://gitlab.com/fdroid/fdroiddata/merge_requests/755
