### ISSUE TITLE
Request for maintenance

### ISSUE THREAD

**Issue by pavi2410** [ligi/AJShA#3]
Can I please maintain this app? I am a regular user of this app and I would like to add some more features to make it even better. Because I don't want to duplicate this app on the Play Store.

**Comment by ligi** [comment]
I am happy about pull requests. If this is what you mean then yes.

**Comment by pavi2410** [comment]
Thanks and yes, this is what I want. I thought you wouldn't merge PR as the last commit was 3 years ago.

**Comment by ligi** [comment]
no there was just no PR for this project. Looking forward to your PRs - closing this issue then.

**Comment by pavi2410** [comment]
Would you mind if I convert the project to Kotlin and follow MVVM architecture?
